http:
  routers:
    proxmox-fenrir:
      rule: "Host(`pve.kluhan.dev`) || Host(`proxmox.kluhan.dev`) || Host(`fenrir.kluhan.dev`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: proxmox-fenrir

    proxmox-draugr:
      rule: "Host(`draugr.kluhan.dev`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: proxmox-fenrir

  services:
    proxmox-fenrir:
      loadBalancer:
        servers:
          - url: "https://192.168.100.10:8006"
        serversTransport: proxmox-transport

    proxmox-draugr:
      loadBalancer:
        servers:
          - url: "https://192.168.100.20:8006"
        serversTransport: proxmox-transport

  serversTransports:
    proxmox-transport:
      insecureSkipVerify: true
