version: "3.8"

networks:
  traefik-public:
    external: true

volumes:
  traefik-acme:

services:
  traefik:
    image: traefik:v3.1
    networks:
      - traefik-public
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-acme:/acme
    secrets:
      - cloudflare_dns_api_token
      - letsencrypt_contact_email
    environment:
      # LEGO (ACME lib) Cloudflare Token:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cloudflare_dns_api_token
    command:
      - --log.level=INFO

      # Swarm provider (Traefik v3)
      - --providers.swarm=true
      - --providers.swarm.exposedbydefault=false
      - --providers.swarm.endpoint=unix:///var/run/docker.sock

      # EntryPoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # Redirect HTTP -> HTTPS
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https

      # ACME DNS-01 via Cloudflare
      - --certificatesresolvers.letsencrypt.acme.emailFile=/run/secrets/letsencrypt_contact_email
      - --certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare

    deploy:
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == polaris
      labels:
        - traefik.enable=true

secrets:
  cloudflare_dns_api_token:
    external: true
  letsencrypt_contact_email:
    external: true
