http:
  routers:
    truenas:
      rule: "Host(`truenas.kluhan.dev`) || Host(`true-nas.kluhan.dev`) || Host(`nas.kluhan.dev`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: truenas

  services:
    truenas:
      loadBalancer:
        servers:
          - url: "https://192.168.100.75"
        serversTransport: truenas-transport

  serversTransports:
    truenas-transport:
      insecureSkipVerify: true
